### PR TITLE
Limit number block asphalt make by moreblocks with an option

### PR DESCRIPTION
**Pull request by Jat15**
Use new api moreblocks.

### CODE REVIEW

**Comment by Thomas--S** [comment]
This is already done in 3.0

**Comment by Jat15** [comment]
Streets 3.0  is fully backwards-compatible to streets 2.x ?

**Comment by Thomas--S** [comment]
Not at the moment, but it will be (nearly) backwards compatible in regards of gameplay when it will be released. The API is not backwards compatible.

**Comment by Jat15** [comment]
Thx

**Pull request closed without merging**
