### PR TITLE
Writeable signs

### PR DESCRIPTION
**Pull request by Thomas--S**
**Please do not merge this yet.** This is only a preview as requested in #60.

You need pyrollo/display_modpack#15 for this to work.

### CODE REVIEW

**Comment by webD97** [comment]
Amazing! I already love it! 
screenshot_20180215_221632

**Comment by Thomas--S** [comment]
screenshot_20180216_173624
screenshot_20180216_174202

**Comment by Thomas--S** [comment]
I'm not sure whether to merge this as-is or to wait for 3.0 for writeable signs.

I think I prefer the second option a little bit. What's your opinion?

I have some further plans for writeable signs in 3.0, so I fear we will have backwards compatiblity problems then when we merge this PR.

**Comment by webD97** [comment]
I support waiting for 3.0 to make sure it's mature and stable enough.

---- Thomas--S schrieb ----


I'm not sure whether to merge this as-is or to wait for 3.0 for writeable signs.

I think I prefer the second option a little bit. What's your opinion?

I have some further plans for writeable signs in 3.0, so I fear we will have backwards compatiblity problems then when we merge this PR.

**Comment by Thomas--S** [comment]
Thanks for your quick answer!

I'll close this PR noew and then open a new one for 3.0 later.

**Pull request closed without merging**
