### PR TITLE
Remove old workshops

### PR DESCRIPTION
**Pull request by Thomas--S**
Submitted as PR, as this may be controversial.
Sign workshop is completely removed (replaced by air) as this causes backwards compatibility problems with Streets 1.x

### CODE REVIEW

**Comment by webD97** [comment]
Sorry, I wasn't able to review this yet. I'll do my best to do this asap.

**Comment by webD97** [comment]
I just took a look at it. The only problem I see is that the asphalt workshop keeps its old formspec because of it just being aliased to the new one. I can live with that because they don't differ visually, so this shouldn't cause too much confusion.

**Comment by Thomas--S** [comment]
Those old formspecs are replaced by the new ones as soon as you click somewhere in the old formspec. Thanks for your review!

**Comment by webD97** [comment]
Oh, ok. I didn't try clicking anything. Sorry for that...

**Comment by Thomas--S** [comment]
No problem :)

**Comment by Thomas--S** [comment]
Thanks for merging!

**Pull request merged**
